//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WfcPatcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wifi.wfc.kthx.at")]
        public string PatchServer {
            get {
                return ((string)(this["PatchServer"]));
            }
            set {
                this["PatchServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>|message|call 1-800-895-1672 in the USA and Canada, or|visit #dreamwfc on Rizon or</string>
  <string>|normal|www.nintendowifi.com|wfc.kthx.at</string>
  <string>|normal|nintendowifi.net|wifi.wfc.kthx.at</string>
  <string>|normal|nintendowifi.com|wfc.kthx.at</string>
  <string>|message|Nintendo Wi-Fi Connection service|the DreamWFC service</string>
  <string>|message|Nintendo Wi-Fi Connection|the DreamWFC servers</string>
  <string>|message|Nintendo WFC|DreamWFC</string>
  <string>|message|Nintendo Wi-Fi|DreamWFC</string>
  <string>|message|DreamWFC data|Wi-Fi data</string>
  <string>|message|DreamWFC ID|Wi-Fi ID</string>
  <string>|message|Wi-Fi  user|Wi-Fi user</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PatchSubstrings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PatchSubstrings"]));
            }
            set {
                this["PatchSubstrings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApplyNoSSL {
            get {
                return ((bool)(this["ApplyNoSSL"]));
            }
            set {
                this["ApplyNoSSL"] = value;
            }
        }
    }
}
